In [2]:
import csv
import pandas as pd
import re

In [3]:
with open("datas/hasetal_distributor_accounts.csv", "r", encoding="utf-8") as f:
    reader = csv.reader(f)

In [4]:
df_dis = pd.read_csv("datas/hasetal_distributor_accounts.csv")
df_dis[1:50]

,account_id,region,account_type,tier,onboarded_date,month,cases_ordered
1,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-08,3
2,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-09,2
3,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-10,3
4,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-11,2
5,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-12,3
6,ACC-1001,Münsterland (NRW),Gastronomie - Bar,B - Regular,2023-07-04,2025-07,5
7,ACC-1001,Münsterland (NRW),Gastronomie - Bar,B - Regular,2023-07-04,2025-08,8
8,ACC-1001,Münsterland (NRW),Gastronomie - Bar,B - Regular,2023-07-04,2025-09,17
9,ACC-1001,Münsterland (NRW),Gastronomie - Bar,B - Regular,2023-07-04,2025-10,14
10,ACC-1001,Münsterland (NRW),Gastronomie - Bar,B - Regular,2023-07-04,2025-11,12
11,ACC-1001,Münsterland (NRW),Gastronomie - Bar,B - Regular,2023-07-04,2025-12,6
12,ACC-1002,Emsland,Gastronomie - Bar,B - Regular,2021-09-23,2025-07,7
13,ACC-1002,Emsland,Gastronomie - Bar,B - Regular,2021-09-23,2025-08,5
14,ACC-1002,Emsland,Gastronomie - Bar,B - Regular,2021-09-23,2025-09,5
15,ACC-1002,Emsland,Gastronomie - Bar,B - Regular,2021-09-23,2025-10,7
16,ACC-1002,Emsland,Gastronomie - Bar,B - Regular,2021-09-23,2025-11,8
17,ACC-1002,Emsland,Gastronomie - Bar,B - Regular,2021-09-23,2025-12,6
18,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-07,5
19,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-08,0
20,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-09,5
21,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-10,0
22,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-11,0
23,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-12,0
24,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-07,4
25,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-08,2
26,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-09,4
27,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-10,4
28,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-11,3
29,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-12,3
30,ACC-1005,Emsland,Getränkemarkt,C - Occasional,2023-06-30,2025-07,4
31,ACC-1005,Emsland,Getränkemarkt,C - Occasional,2023-06-30,2025-08,4
32,ACC-1005,Emsland,Getränkemarkt,C - Occasional,2023-06-30,2025-09,2
33,ACC-1005,Emsland,Getränkemarkt,C - Occasional,2023-06-30,2025-10,4
34,ACC-1005,Emsland,Getränkemarkt,C - Occasional,2023-06-30,2025-11,2
35,ACC-1005,Emsland,Getränkemarkt,C - Occasional,2023-06-30,2025-12,2
36,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-07,1
37,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-08,1
38,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-09,3
39,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-10,2
40,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-11,3
41,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-12,4
42,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-07,3
43,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-08,4
44,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-09,1
45,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-10,2
46,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-11,0
47,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-12,0
48,ACC-1008,Landkreis Osnabrück,Gastronomie - Bar,A - Key Account,2023-10-04,2025-07,20
49,ACC-1008,Landkreis Osnabrück,Gastronomie - Bar,A - Key Account,2023-10-04,2025-08,31

In [5]:
len(df_dis['account_id'].drop_duplicates().to_list())

42

In [6]:
grouped_distr_pre_month = df_dis.groupby(['month', 'account_type'])['cases_ordered']

data_distr_tim_ordered = grouped_distr_pre_month.sum().reset_index()

data_distr_tim_ordered.to_csv("datas/orders_time_line.csv")
data_distr_tim_ordered

      month              account_type  cases_ordered
0   2025-07                Fachhandel             84
1   2025-07         Gastronomie - Bar            153
2   2025-07  Gastronomie - Restaurant             99
3   2025-07             Getränkemarkt             56
4   2025-08                Fachhandel            100
5   2025-08         Gastronomie - Bar            124
6   2025-08  Gastronomie - Restaurant             71
7   2025-08             Getränkemarkt             38
8   2025-09                Fachhandel             68
9   2025-09         Gastronomie - Bar            143
10  2025-09  Gastronomie - Restaurant             59
11  2025-09             Getränkemarkt             46
12  2025-10                Fachhandel             73
13  2025-10         Gastronomie - Bar            141
14  2025-10  Gastronomie - Restaurant             60
15  2025-10             Getränkemarkt             49
16  2025-11                Fachhandel             90
17  2025-11         Gastronomie - Bar            144
18  2025-11  Gastronomie - Restaurant             55
19  2025-11             Getränkemarkt             59
20  2025-12                Fachhandel             92
21  2025-12         Gastronomie - Bar            126
22  2025-12  Gastronomie - Restaurant             75
23  2025-12             Getränkemarkt             46

In [7]:

zero_case_orders = df_dis[df_dis["cases_ordered"] == 0]
zero_case_orders

,account_id,region,account_type,tier,onboarded_date,month,cases_ordered
19,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-08,0
21,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-10,0
22,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-11,0
23,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-12,0
46,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-11,0
47,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-12,0
74,ACC-1012,Landkreis Osnabrück,Gastronomie - Bar,C - Occasional,2022-07-31,2025-09,0
75,ACC-1012,Landkreis Osnabrück,Gastronomie - Bar,C - Occasional,2022-07-31,2025-10,0
76,ACC-1012,Landkreis Osnabrück,Gastronomie - Bar,C - Occasional,2022-07-31,2025-11,0
77,ACC-1012,Landkreis Osnabrück,Gastronomie - Bar,C - Occasional,2022-07-31,2025-12,0
111,ACC-1018,Oldenburg,Getränkemarkt,C - Occasional,2022-03-05,2025-10,0
112,ACC-1018,Oldenburg,Getränkemarkt,C - Occasional,2022-03-05,2025-11,0
113,ACC-1018,Oldenburg,Getränkemarkt,C - Occasional,2022-03-05,2025-12,0
115,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-08,0
116,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-09,0
118,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-11,0
119,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-12,0
128,ACC-1021,Oldenburg,Fachhandel,C - Occasional,2023-01-24,2025-09,0
129,ACC-1021,Oldenburg,Fachhandel,C - Occasional,2023-01-24,2025-10,0
130,ACC-1021,Oldenburg,Fachhandel,C - Occasional,2023-01-24,2025-11,0
131,ACC-1021,Oldenburg,Fachhandel,C - Occasional,2023-01-24,2025-12,0
134,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-09,0
135,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-10,0
136,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-11,0
137,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-12,0
205,ACC-1034,Landkreis Osnabrück,Fachhandel,C - Occasional,2024-03-30,2025-08,0
207,ACC-1034,Landkreis Osnabrück,Fachhandel,C - Occasional,2024-03-30,2025-10,0
208,ACC-1034,Landkreis Osnabrück,Fachhandel,C - Occasional,2024-03-30,2025-11,0
209,ACC-1034,Landkreis Osnabrück,Fachhandel,C - Occasional,2024-03-30,2025-12,0
217,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-08,0
218,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-09,0
219,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-10,0
220,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-11,0
221,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-12,0

In [8]:
len(zero_case_orders)
zero_ordered_olds = zero_case_orders["account_id"].drop_duplicates().to_list()
zero_ordered_olds

['ACC-1003',
 'ACC-1007',
 'ACC-1012',
 'ACC-1018',
 'ACC-1019',
 'ACC-1021',
 'ACC-1022',
 'ACC-1034',
 'ACC-1036']

# To better understand the critical situation, I am separately counting zero orders from regular customers.

In [9]:
critical_could_be = zero_case_orders[zero_case_orders["tier"].str.contains("B")]
critical_could_be

,account_id,region,account_type,tier,onboarded_date,month,cases_ordered
115,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-08,0
116,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-09,0
118,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-11,0
119,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-12,0
217,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-08,0
218,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-09,0
219,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-10,0
220,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-11,0
221,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-12,0

In [10]:
df_dis[df_dis['tier'].str.contains('C')]

,account_id,region,account_type,tier,onboarded_date,month,cases_ordered
0,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-07,4
1,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-08,3
2,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-09,2
3,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-10,3
4,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-11,2
...,...,...,...,...,...,...,...
241,ACC-1040,Emsland,Gastronomie - Bar,C - Occasional,2022-03-13,2025-08,1
242,ACC-1040,Emsland,Gastronomie - Bar,C - Occasional,2022-03-13,2025-09,2
243,ACC-1040,Emsland,Gastronomie - Bar,C - Occasional,2022-03-13,2025-10,3
244,ACC-1040,Emsland,Gastronomie - Bar,C - Occasional,2022-03-13,2025-11,2
245,ACC-1040,Emsland,Gastronomie - Bar,C - Occasional,2022-03-13,2025-12,2

In [11]:
should_cleaned_with_doublicats = df_dis.sort_values(ascending=True, by="onboarded_date")
should_cleaned_with_doublicats[1:50]

,account_id,region,account_type,tier,onboarded_date,month,cases_ordered
27,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-10,4
28,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-11,3
29,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-12,3
25,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-08,2
24,ACC-1004,Oldenburg,Gastronomie - Bar,C - Occasional,2021-01-02,2025-07,4
202,ACC-1033,Emsland,Gastronomie - Bar,B - Regular,2021-01-12,2025-11,6
201,ACC-1033,Emsland,Gastronomie - Bar,B - Regular,2021-01-12,2025-10,14
199,ACC-1033,Emsland,Gastronomie - Bar,B - Regular,2021-01-12,2025-08,9
198,ACC-1033,Emsland,Gastronomie - Bar,B - Regular,2021-01-12,2025-07,9
203,ACC-1033,Emsland,Gastronomie - Bar,B - Regular,2021-01-12,2025-12,4
200,ACC-1033,Emsland,Gastronomie - Bar,B - Regular,2021-01-12,2025-09,8
227,ACC-1037,Landkreis Osnabrück,Fachhandel,B - Regular,2021-02-19,2025-12,6
226,ACC-1037,Landkreis Osnabrück,Fachhandel,B - Regular,2021-02-19,2025-11,7
225,ACC-1037,Landkreis Osnabrück,Fachhandel,B - Regular,2021-02-19,2025-10,10
224,ACC-1037,Landkreis Osnabrück,Fachhandel,B - Regular,2021-02-19,2025-09,7
223,ACC-1037,Landkreis Osnabrück,Fachhandel,B - Regular,2021-02-19,2025-08,12
222,ACC-1037,Landkreis Osnabrück,Fachhandel,B - Regular,2021-02-19,2025-07,11
216,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-07,11
221,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-12,0
220,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-11,0
219,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-10,0
218,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-09,0
217,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-08,0
132,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-07,2
133,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-08,4
134,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-09,0
135,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-10,0
136,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-11,0
137,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-12,0
197,ACC-1032,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2021-05-25,2025-12,27
192,ACC-1032,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2021-05-25,2025-07,24
193,ACC-1032,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2021-05-25,2025-08,12
194,ACC-1032,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2021-05-25,2025-09,17
195,ACC-1032,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2021-05-25,2025-10,11
196,ACC-1032,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2021-05-25,2025-11,24
92,ACC-1015,Oldenburg,Gastronomie - Restaurant,C - Occasional,2021-06-06,2025-09,4
93,ACC-1015,Oldenburg,Gastronomie - Restaurant,C - Occasional,2021-06-06,2025-10,3
94,ACC-1015,Oldenburg,Gastronomie - Restaurant,C - Occasional,2021-06-06,2025-11,3
95,ACC-1015,Oldenburg,Gastronomie - Restaurant,C - Occasional,2021-06-06,2025-12,4
91,ACC-1015,Oldenburg,Gastronomie - Restaurant,C - Occasional,2021-06-06,2025-08,2
90,ACC-1015,Oldenburg,Gastronomie - Restaurant,C - Occasional,2021-06-06,2025-07,3
177,ACC-1029,Emsland,Fachhandel,B - Regular,2021-06-26,2025-10,6
176,ACC-1029,Emsland,Fachhandel,B - Regular,2021-06-26,2025-09,10
179,ACC-1029,Emsland,Fachhandel,B - Regular,2021-06-26,2025-12,18
174,ACC-1029,Emsland,Fachhandel,B - Regular,2021-06-26,2025-07,11
178,ACC-1029,Emsland,Fachhandel,B - Regular,2021-06-26,2025-11,7
175,ACC-1029,Emsland,Fachhandel,B - Regular,2021-06-26,2025-08,13
40,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-11,3
39,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-10,2

In [12]:
no_double_time_based = should_cleaned_with_doublicats.drop_duplicates(subset="account_id")[1:31]
no_double_time_based

total_distrubuter_count = len(no_double_time_based["account_id"])
total_distrubuter_count

a_cat_count = len(no_double_time_based[no_double_time_based["tier"].str.contains('A')])

b_cat_count = len(no_double_time_based[no_double_time_based["tier"].str.contains('B')])

c_cat_count = len(no_double_time_based[no_double_time_based["tier"].str.contains('C')])

print(f" >> First 30 costums from 2021-01-02 to 2023-06-30")
print(f"Category A -- Account distributers total count : {a_cat_count}")
print(f"Category B -- Regular distributors total count : {b_cat_count}")
print(f"Category C -- Occasional distributors total count : {c_cat_count}")

 >> First 30 costums from 2021-01-02 to 2023-06-30
Category A -- Account distributers total count : 6
Category B -- Regular distributors total count : 10
Category C -- Occasional distributors total count : 14

In [13]:
no_double_time_based

,account_id,region,account_type,tier,onboarded_date,month,cases_ordered
202,ACC-1033,Emsland,Gastronomie - Bar,B - Regular,2021-01-12,2025-11,6
227,ACC-1037,Landkreis Osnabrück,Fachhandel,B - Regular,2021-02-19,2025-12,6
216,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-07,11
132,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-07,2
197,ACC-1032,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2021-05-25,2025-12,27
92,ACC-1015,Oldenburg,Gastronomie - Restaurant,C - Occasional,2021-06-06,2025-09,4
177,ACC-1029,Emsland,Fachhandel,B - Regular,2021-06-26,2025-10,6
40,ACC-1006,Emsland,Fachhandel,C - Occasional,2021-07-28,2025-11,3
0,ACC-1000,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2021-08-19,2025-07,4
66,ACC-1011,Bremen,Gastronomie - Bar,B - Regular,2021-09-13,2025-07,11
17,ACC-1002,Emsland,Gastronomie - Bar,B - Regular,2021-09-23,2025-12,6
23,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-12,0
228,ACC-1038,Grafschaft Bentheim,Fachhandel,A - Key Account,2022-01-02,2025-07,7
110,ACC-1018,Oldenburg,Getränkemarkt,C - Occasional,2022-03-05,2025-09,2
244,ACC-1040,Emsland,Gastronomie - Bar,C - Occasional,2022-03-13,2025-11,2
165,ACC-1027,Münsterland (NRW),Gastronomie - Bar,A - Key Account,2022-03-17,2025-10,10
80,ACC-1013,Osnabrück Stadt,Fachhandel,C - Occasional,2022-04-07,2025-09,3
234,ACC-1039,Landkreis Osnabrück,Gastronomie - Bar,C - Occasional,2022-05-06,2025-07,3
121,ACC-1020,Grafschaft Bentheim,Fachhandel,B - Regular,2022-06-04,2025-08,16
159,ACC-1026,Emsland,Getränkemarkt,B - Regular,2022-06-06,2025-10,9
89,ACC-1014,Landkreis Osnabrück,Fachhandel,A - Key Account,2022-06-24,2025-12,21
42,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-07,3
76,ACC-1012,Landkreis Osnabrück,Gastronomie - Bar,C - Occasional,2022-07-31,2025-11,0
107,ACC-1017,Emsland,Gastronomie - Restaurant,B - Regular,2022-09-05,2025-12,7
181,ACC-1030,Osnabrück Stadt,Fachhandel,C - Occasional,2022-10-02,2025-08,3
246,ACC-1041,Landkreis Osnabrück,Gastronomie - Restaurant,A - Key Account,2022-10-10,2025-07,23
130,ACC-1021,Oldenburg,Fachhandel,C - Occasional,2023-01-24,2025-11,0
215,ACC-1035,Bremen,Gastronomie - Bar,A - Key Account,2023-03-20,2025-12,26
118,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-11,0
35,ACC-1005,Emsland,Getränkemarkt,C - Occasional,2023-06-30,2025-12,2

In [14]:
no_double_time_based[no_double_time_based['account_id'].isin(zero_ordered_olds)]

,account_id,region,account_type,tier,onboarded_date,month,cases_ordered
216,ACC-1036,Münsterland (NRW),Fachhandel,B - Regular,2021-03-11,2025-07,11
132,ACC-1022,Landkreis Osnabrück,Gastronomie - Restaurant,C - Occasional,2021-05-24,2025-07,2
23,ACC-1003,Münsterland (NRW),Gastronomie - Restaurant,C - Occasional,2021-09-27,2025-12,0
110,ACC-1018,Oldenburg,Getränkemarkt,C - Occasional,2022-03-05,2025-09,2
42,ACC-1007,Osnabrück Stadt,Gastronomie - Restaurant,C - Occasional,2022-07-15,2025-07,3
76,ACC-1012,Landkreis Osnabrück,Gastronomie - Bar,C - Occasional,2022-07-31,2025-11,0
130,ACC-1021,Oldenburg,Fachhandel,C - Occasional,2023-01-24,2025-11,0
118,ACC-1019,Osnabrück Stadt,Gastronomie - Restaurant,B - Regular,2023-04-03,2025-11,0

In [15]:
groped_more_ordered_costum =  df_dis.groupby(['account_id', 'account_type', 'tier'])['cases_ordered']
most_ordered_distributers = groped_more_ordered_costum.sum().sort_values(ascending=False)[1:10]
most_ordered_distributers = most_ordered_distributers.reset_index()
most_ordered_distributers

  account_id              account_type             tier  cases_ordered
0   ACC-1008         Gastronomie - Bar  A - Key Account            136
1   ACC-1016         Gastronomie - Bar  A - Key Account            134
2   ACC-1035         Gastronomie - Bar  A - Key Account            128
3   ACC-1038                Fachhandel  A - Key Account            125
4   ACC-1041  Gastronomie - Restaurant  A - Key Account            123
5   ACC-1024             Getränkemarkt  A - Key Account            118
6   ACC-1014                Fachhandel  A - Key Account            117
7   ACC-1032  Gastronomie - Restaurant  A - Key Account            115
8   ACC-1029                Fachhandel      B - Regular             65

In [16]:
most_ordered_distributers.to_csv('datas/most_ordered_costums.csv')

In [17]:
df_month = pd.read_csv("datas/hasetal_monthly_sales.csv")
df_month.sort_values(ascending=True, by='month')

,month,product_line,channel,cases_sold,avg_price_per_case_eur,revenue_eur
0,2024-01,Hasetal Dry Gin,Fachhandel (Distributor),456,19.52,8900.53
72,2024-01,Hasetal Dry Gin,Hofladen/Tasting Room,224,24.77,5548.57
120,2024-01,Hasetal Sloe Gin (Saison),Gastronomie (On-Premise),81,25.99,2105.13
144,2024-01,Hasetal Sloe Gin (Saison),DTC Online,58,31.81,1844.85
48,2024-01,Hasetal Dry Gin,DTC Online,160,28.40,4543.31
...,...,...,...,...,...,...
307,2025-12,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),81,18.29,1481.65
239,2025-12,Alte Sorte Obstbrand,Gastronomie (On-Premise),56,19.03,1065.53
95,2025-12,Hasetal Dry Gin,Hofladen/Tasting Room,219,26.31,5762.05
317,2025-12,Hasetal Alkoholfrei Botanical,DTC Online,182,22.39,4075.89
327,2025-12,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,103,20.00,2059.76

In [18]:
total_saled_rpoduct_rpo_channel = df_month.groupby('channel')['product_line']
total_saled_rpoduct_rpo_channel.count()

channel
DTC Online                  82
Fachhandel (Distributor)    82
Gastronomie (On-Premise)    82
Hofladen/Tasting Room       82
Name: product_line, dtype: int64

In [19]:
products = set(df_month["product_line"])
print(products, f"\nTOTAL : {len(products)}")

product_count = df_month["product_line"].value_counts()
print("\n\n",product_count)

{'Alte Sorte Obstbrand', 'Hasetal Alkoholfrei Botanical', 'Hasetal Sloe Gin (Saison)', 'Hasetal Dry Gin'}
TOTAL : 4


 product_line
Hasetal Dry Gin                  96
Hasetal Sloe Gin (Saison)        96
Alte Sorte Obstbrand             96
Hasetal Alkoholfrei Botanical    40
Name: count, dtype: int64

## TOTAL 4 products

*and count of them*

In [20]:
df_month.columns

Index(['month', 'product_line', 'channel', 'cases_sold',
       'avg_price_per_case_eur', 'revenue_eur'],
      dtype='str')

In [ ]:
df_month[df_month['product_line'].str.contains('Alkoholfrei')]

,month,product_line,channel,cases_sold,avg_price_per_case_eur,revenue_eur
288,2025-03,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),81,15.11,1223.84
289,2025-04,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),107,15.30,1637.12
290,2025-05,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),97,14.31,1387.94
291,2025-06,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),133,14.83,1971.90
292,2025-07,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),116,14.79,1715.56
293,2025-08,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),126,14.74,1856.72
294,2025-09,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),124,14.56,1805.09
295,2025-10,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),138,14.56,2009.10
296,2025-11,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),136,14.85,2019.23
297,2025-12,Hasetal Alkoholfrei Botanical,Fachhandel (Distributor),148,15.47,2289.23
298,2025-03,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),35,19.11,668.70
299,2025-04,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),56,17.35,971.56
300,2025-05,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),53,18.29,969.57
301,2025-06,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),52,18.07,939.55
302,2025-07,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),57,19.47,1109.93
303,2025-08,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),73,19.21,1402.02
304,2025-09,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),76,17.87,1358.38
305,2025-10,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),72,18.77,1351.56
306,2025-11,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),71,18.90,1341.60
307,2025-12,Hasetal Alkoholfrei Botanical,Gastronomie (On-Premise),81,18.29,1481.65
308,2025-03,Hasetal Alkoholfrei Botanical,DTC Online,71,21.56,1530.66
309,2025-04,Hasetal Alkoholfrei Botanical,DTC Online,75,22.01,1651.12
310,2025-05,Hasetal Alkoholfrei Botanical,DTC Online,81,21.67,1755.12
311,2025-06,Hasetal Alkoholfrei Botanical,DTC Online,109,21.08,2297.44
312,2025-07,Hasetal Alkoholfrei Botanical,DTC Online,121,20.48,2477.65
313,2025-08,Hasetal Alkoholfrei Botanical,DTC Online,144,21.16,3046.61
314,2025-09,Hasetal Alkoholfrei Botanical,DTC Online,142,21.94,3116.12
315,2025-10,Hasetal Alkoholfrei Botanical,DTC Online,156,20.38,3178.66
316,2025-11,Hasetal Alkoholfrei Botanical,DTC Online,160,21.66,3465.89
317,2025-12,Hasetal Alkoholfrei Botanical,DTC Online,182,22.39,4075.89
318,2025-03,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,53,19.55,1036.04
319,2025-04,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,51,19.66,1002.54
320,2025-05,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,65,19.49,1266.95
321,2025-06,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,63,19.39,1221.68
322,2025-07,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,60,18.64,1118.36
323,2025-08,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,79,19.32,1526.10
324,2025-09,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,85,19.11,1624.39
325,2025-10,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,88,18.85,1659.23
326,2025-11,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,80,20.02,1601.98
327,2025-12,Hasetal Alkoholfrei Botanical,Hofladen/Tasting Room,103,20.00,2059.76

In [21]:
grouped_month = df_month.groupby(["product_line","channel" ])["revenue_eur"]
for_grouped_sum = grouped_month.sum().sort_values(ascending=False)
for_grouped_sum

product_line                   channel
Hasetal Dry Gin                DTC Online                  188068.43
                               Fachhandel (Distributor)    177233.88
                               Hofladen/Tasting Room       134212.10
                               Gastronomie (On-Premise)    123431.54
Hasetal Sloe Gin (Saison)      DTC Online                   78744.54
                               Fachhandel (Distributor)     68579.97
Alte Sorte Obstbrand           Fachhandel (Distributor)     64533.70
                               DTC Online                   64291.64
Hasetal Sloe Gin (Saison)      Hofladen/Tasting Room        53968.79
                               Gastronomie (On-Premise)     50340.52
Alte Sorte Obstbrand           Hofladen/Tasting Room        46956.66
                               Gastronomie (On-Premise)     43142.98
Hasetal Alkoholfrei Botanical  DTC Online                   26595.16
                               Fachhandel (Distributor)     17915.73
                               Hofladen/Tasting Room        14117.03
                               Gastronomie (On-Premise)     11594.52
Name: revenue_eur, dtype: float64

In [22]:
result_of_grouped_sum = for_grouped_sum.reset_index()
result_of_grouped_sum.columns = ['Product', 'Channel', 'Revenue EUR']
result_of_grouped_sum

                          Product                   Channel  Revenue EUR
0                 Hasetal Dry Gin                DTC Online    188068.43
1                 Hasetal Dry Gin  Fachhandel (Distributor)    177233.88
2                 Hasetal Dry Gin     Hofladen/Tasting Room    134212.10
3                 Hasetal Dry Gin  Gastronomie (On-Premise)    123431.54
4       Hasetal Sloe Gin (Saison)                DTC Online     78744.54
5       Hasetal Sloe Gin (Saison)  Fachhandel (Distributor)     68579.97
6            Alte Sorte Obstbrand  Fachhandel (Distributor)     64533.70
7            Alte Sorte Obstbrand                DTC Online     64291.64
8       Hasetal Sloe Gin (Saison)     Hofladen/Tasting Room     53968.79
9       Hasetal Sloe Gin (Saison)  Gastronomie (On-Premise)     50340.52
10           Alte Sorte Obstbrand     Hofladen/Tasting Room     46956.66
11           Alte Sorte Obstbrand  Gastronomie (On-Premise)     43142.98
12  Hasetal Alkoholfrei Botanical                DTC Online     26595.16
13  Hasetal Alkoholfrei Botanical  Fachhandel (Distributor)     17915.73
14  Hasetal Alkoholfrei Botanical     Hofladen/Tasting Room     14117.03
15  Hasetal Alkoholfrei Botanical  Gastronomie (On-Premise)     11594.52

In [23]:
result_of_grouped_sum.to_csv("datas/sum_product_pre_chanel.csv", index=False, encoding="utf-8-sig")

In [24]:
data_alkolfrei = df_month[df_month['product_line'] == "Hasetal Alkoholfrei Botanical"]

grouped_alkolfrei_pre_channel = data_alkolfrei.groupby('channel')['revenue_eur']

grouped_alkolfrei_pre_channel.sum()

channel
DTC Online                  26595.16
Fachhandel (Distributor)    17915.73
Gastronomie (On-Premise)    11594.52
Hofladen/Tasting Room       14117.03
Name: revenue_eur, dtype: float64

In [25]:
df_surver = pd.read_csv('datas/hasetal_visitor_survey.csv')
df_surver

,respondent_id,visit_month,age_group,discovery_channel,preferred_purchase_channel,alcohol_consumption_change_12m,interest_in_alkoholfrei_line,nps_score_0_10
0,R-2000,2025-02,18-24,Instagram/Social Media,Gastronomie,"Ja, deutlich weniger",Vielleicht,9
1,R-2001,2025-02,65+,Wochenmarkt/Event,Online-Shop (DTC),Unverändert,"Nein, kein Interesse",9
2,R-2002,2025-04,65+,Empfehlung (Word of Mouth),Hofladen (vor Ort),Unverändert,Vielleicht,8
3,R-2003,2025-09,35-44,Google-Suche,Fachhandel,Unverändert,"Nein, kein Interesse",6
4,R-2004,2025-07,45-54,Empfehlung (Word of Mouth),Hofladen (vor Ort),"Ja, etwas weniger","Ja, interessiert",9
...,...,...,...,...,...,...,...,...
175,R-2175,2025-03,65+,Fachhandel-Regal,Hofladen (vor Ort),"Ja, etwas weniger",Vielleicht,8
176,R-2176,2025-04,25-34,Empfehlung (Word of Mouth),Hofladen (vor Ort),"Ja, deutlich weniger","Ja, interessiert",10
177,R-2177,2025-07,35-44,Empfehlung (Word of Mouth),Fachhandel,"Ja, deutlich weniger","Nein, kein Interesse",5
178,R-2178,2025-09,18-24,Google-Suche,Online-Shop (DTC),"Ja, deutlich weniger",Vielleicht,8
179,R-2179,2025-09,55-64,Instagram/Social Media,Hofladen (vor Ort),"Ja, deutlich weniger","Nein, kein Interesse",6

In [26]:
list_of_fiscover = df_surver['discovery_channel'].unique()
list_of_fiscover

<StringArray>
[    'Instagram/Social Media',          'Wochenmarkt/Event',
 'Empfehlung (Word of Mouth)',               'Google-Suche',
                  'Sonstiges',           'Fachhandel-Regal']
Length: 6, dtype: str

In [27]:
age_goruped = pd.crosstab(df_surver['age_group'], df_surver['alcohol_consumption_change_12m'])
age_goruped.to_csv('datas/age_grouped_consum.csv')

In [28]:
def change_to_short(discovery):
    if discovery in ['Google-Suche','Instagram/Social Media']:
        return 'online'
    if discovery in ['Empfehlung (Word of Mouth)', 'Sonstiges']:
        return 'heard'
    if discovery in ['Wochenmarkt/Event', 'Fachhandel-Regal' ]:
        return 'physical contact'


df_surver['psy_cat'] = df_surver['discovery_channel'].apply(change_to_short)

df_surver.head(20)

,respondent_id,visit_month,age_group,discovery_channel,preferred_purchase_channel,alcohol_consumption_change_12m,interest_in_alkoholfrei_line,nps_score_0_10,psy_cat
0,R-2000,2025-02,18-24,Instagram/Social Media,Gastronomie,"Ja, deutlich weniger",Vielleicht,9,online
1,R-2001,2025-02,65+,Wochenmarkt/Event,Online-Shop (DTC),Unverändert,"Nein, kein Interesse",9,physical contact
2,R-2002,2025-04,65+,Empfehlung (Word of Mouth),Hofladen (vor Ort),Unverändert,Vielleicht,8,heard
3,R-2003,2025-09,35-44,Google-Suche,Fachhandel,Unverändert,"Nein, kein Interesse",6,online
4,R-2004,2025-07,45-54,Empfehlung (Word of Mouth),Hofladen (vor Ort),"Ja, etwas weniger","Ja, interessiert",9,heard
5,R-2005,2025-05,45-54,Instagram/Social Media,Hofladen (vor Ort),Unverändert,"Ja, interessiert",9,online
6,R-2006,2025-07,65+,Empfehlung (Word of Mouth),Hofladen (vor Ort),"Ja, etwas weniger",Vielleicht,8,heard
7,R-2007,2025-09,35-44,Instagram/Social Media,Fachhandel,Unverändert,Vielleicht,9,online
8,R-2008,2025-11,45-54,Empfehlung (Word of Mouth),Hofladen (vor Ort),"Ja, etwas weniger","Ja, interessiert",10,heard
9,R-2009,2025-01,25-34,Wochenmarkt/Event,Online-Shop (DTC),Unverändert,"Nein, kein Interesse",6,physical contact
10,R-2010,2025-04,25-34,Instagram/Social Media,Hofladen (vor Ort),Unverändert,Vielleicht,8,online
11,R-2011,2025-03,35-44,Sonstiges,Online-Shop (DTC),Unverändert,"Nein, kein Interesse",7,heard
12,R-2012,2025-08,25-34,Wochenmarkt/Event,Hofladen (vor Ort),"Ja, etwas weniger","Ja, interessiert",7,physical contact
13,R-2013,2025-04,18-24,Empfehlung (Word of Mouth),Fachhandel,"Ja, etwas weniger","Ja, interessiert",9,heard
14,R-2014,2025-06,35-44,Fachhandel-Regal,Gastronomie,Unverändert,"Ja, interessiert",7,physical contact
15,R-2015,2025-08,45-54,Instagram/Social Media,Hofladen (vor Ort),Unverändert,Vielleicht,7,online
16,R-2016,2025-01,25-34,Empfehlung (Word of Mouth),Online-Shop (DTC),Unverändert,Vielleicht,8,heard
17,R-2017,2025-07,55-64,Sonstiges,Online-Shop (DTC),"Ja, etwas weniger",Vielleicht,9,heard
18,R-2018,2025-01,45-54,Instagram/Social Media,Fachhandel,"Ja, etwas weniger",Vielleicht,9,online
19,R-2019,2025-06,45-54,Google-Suche,Hofladen (vor Ort),Unverändert,"Ja, interessiert",10,online

In [51]:
grouped_psy_and_nps = df_surver.groupby('psy_cat')['nps_score_0_10']
grouped_mean_nps = grouped_psy_and_nps.mean().reset_index().sort_values(by='nps_score_0_10' ,ascending=False)
grouped_mean_nps= grouped_mean_nps.rename(columns={'nps_score_0_10':'mean_of_nps_score'})
grouped_mean_nps['mean_of_nps_score'] = grouped_mean_nps['mean_of_nps_score'].round(2)
grouped_mean_nps

            psy_cat  mean_of_nps_score
0             heard               8.13
1            online               8.04
2  physical contact               8.02

In [32]:
prefer_pre_psy_cat = pd.crosstab(df_surver['psy_cat'], df_surver['preferred_purchase_channel'])
prefer_pre_psy_cat.sort_values(by='Hofladen (vor Ort)', ascending=False).reset_index().to_csv('datas/prefer_to_find.csv')

In [61]:
df_surver['interest_in_alkoholfrei_line'].to_list()
alkol_frei_counts = pd.crosstab(df_surver['preferred_purchase_channel'], df_surver['interest_in_alkoholfrei_line'])
alkol_frei_counts.to_csv('datas/interest_alkolfrei.csv')